---
abstract: 'Modules to represent and manipulate communities of biological organisms'
author:
  - 'BioPerl Team <bioperl-l@bioperl.org>'
build_requires:
  Test::Number::Delta: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Community
provides:
  Bio::Community::Member:
    file: lib/Bio/Community/Member.pm
recommends:
  Math::BigInt::GMP: 0
requires:
  Bio::Root::Version: 1.006910
  DateTime: 0
  Getopt::Euclid: v0.4.3
  Hash::Util: 0
  JSON::XS: 0
  Math::Random::MT: 0
  Method::Signatures: 0
  Moose: 0
  MooseX::NonMoose: 0
  MooseX::StrictConstructor: 0
  Parallel::Iterator: 0
  PerlIO::eol: 0
  Scalar::Util: 0
  Tie::IxHash: 0
  perl: v5.10.0
resources:
  bugtracker: https://redmine.open-bio.org/projects/bioperl/
  homepage: http://www.bioperl.org
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bioperl/Bio-Community.git
version: 0.001000002
